fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
      - id: yamllint
        name: Check YAML files with yamllint
        language: system
        types: [yaml]
        entry: poetry run yamllint
